#!/usr/bin/perl -w
# -*- cperl -*-

use MTY::Common::Common;
use MTY::Common::CommandLine;
use MTY::Common::PrintDebug;
use MTY::Filesystem::Files;
use MTY::Display::Colorize;
use MTY::Display::ColorizeErrorsAndWarnings;
use MTY::Display::DataStructures;
use MTY::Display::Tree;
use MTY::Display::TreeBuilder;
use MTY::Display::TextInABox;

use Storable;

my %command_line_options = ( );

# my ($lines, $invalid_args) = parse_and_check_command_line(%command_line_options);

my @filenames = @ARGV;

my $error_count = 0;

foreach my $filename (@filenames) {
  my $obj = Storable::retrieve($filename);

  if (!defined $obj) { 
    warning('Could not retrieve from storable file ', 
            $filename, ' (error ', $?, '; skipping');
    $error_count++;
    next;
  }

  prints(print_folder_tab(Y.$filename, ORANGE_2_3));
  pp $obj, R.'Perl Storable structure from '.Y.$filename;
  prints(NL);

  $obj = undef; # force it to be garbage collected immediately
}

exit (min($error_count, 255));

