#!/usr/bin/perl -w
# -*- cperl -*-

sub format_char($) {
  my ($i) = @_;
  my $printable = ($i >= 32 && $i < 128);

  return sprintf(
    $printable ? '%-4s' : '<%02x>',
    $printable ? chr($i) : $i);
}

my $str = $ARGV[0];

if (@ARGV) {
  my @chars = map {
    (($_ =~ /\A 0 (?> x[0-9A-Fa-f]+ | b[01]+ | [0-9]+)? \Z/oax) 
      ? oct($_) : (map { ord } split(//, $_)));
  } @ARGV;

  for my $i (0..$#chars) {    
    my $c = $chars[$i];
    printf("  (@ %4d)  %3d  0x%02x  %s\n", 
      $i, $c, $c, format_char($c));
  }
} else {
  print("\n".(' ' x 12));
  for my $i (0..15) { printf('%x/%-2d ', $i, $i); }

  for my $i (0..255) { 
    if (($i & 0xf) == 0) 
      { printf("\n".' %3d  0x%02x ', $i, $i); }
    print(' '.format_char($i));
  };
  print("\n\n");
}
