#
# Convenient alias for MTY::Display::DataStructures package
# so you can simply use "use DDS; pp ..."
#

package DDS;

use Exporter qw(import);
use MTY::Display::DataStructures qw(pp);

our @EXPORT = # (auto-generated by perl-mod-deps)
  qw();

