# -*- cperl -*-
# 
# MTY::PerlModDeps::All
#
# Module bundle (automatically generated by perl-mod-deps)
#

package MTY::PerlModDeps::All;

use MTY::PerlModDeps::Module;

use Exporter::Lite;
nobundle:; preserve:; our @EXPORT = # (auto-generated by perl-mod-deps)
(
  @MTY::PerlModDeps::Module::EXPORT,
);


our @EXPORT_OK = # (auto-generated by perl-mod-deps)
(
  @MTY::PerlModDeps::Module::EXPORT_OK,
);


1;

