#!/usr/bin/perl -w
# -*- cperl -*-
#
# perl-mod-deps:
#
# Copyright 2014 Matt T. Yourst <yourst@yourst.com>
#
# (See MTY/PerlModDeps/PerlModDeps.pm for documentation)
#

use MTY::PerlModDeps::Main;

main(@ARGV);
