#!/usr/bin/perl -w
# -*- cperl -*-
#
# perl-mod-deps:
#
# Copyright 2015 Matt T. Yourst <yourst@yourst.com>
#
# (See MTY/PerlModDeps/PerlModDeps.pm for documentation)
#

# use MTY::Common::ModuleCache;
use MTY::PerlModDeps::Main;

main(@ARGV);
