#!/usr/bin/perl -w

#! autoimport {
#! } # (end autoimport)

$tag = $ARGV[0];

$outenable = 1;
$newoutenable = 1;

while (<STDIN>) {
  $line = $_;

  if (/\#ifdef\s*(\w+)$/) {
    if ($1 eq $tag) {
      $outenable = 0;
      $newoutenable = 0;
    }
  } elsif (/\#ifndef\s*(\w+)$/) {
    if ($1 eq $tag) {
      $outenable = 0;
      $newoutenable = 1;
    }
  } elsif (/\#endif\s*\/\/\s*(\w+)/) {
    if ($1 eq $tag) {
      $outenable = 0;
      $newoutenable = 1;
    }
  }

  if ($outenable) {
    print($line);
  }

  $outenable = $newoutenable;
}
