#!/usr/bin/perl -w
my @iplist = @ARGV;
my $out = '';

foreach my $ip (@iplist) {
  $out .= ((length($out) > 0) ? ' ' : '').$ip;
  $out =~ s[\b (\d+ \. \d+ \. \d+ \.) 
            (?| (\d+) | \{ ([^\}]+) \} )
            \s+ \g{1} (\d+)]
           [${1}{${2},${3}}]oaxg;
}

print($out."\n");

