#!/usr/bin/perl -w
# -*- cperl -*-
#
# update-ifdefs:
# Inserts, updates and maintains #if / #ifdef / #else / #elif / #endif
# preprocessor commands in both C/C++ source files and their headers:
#
# - Automatically adds guards to prevent redundant header inclusion
#   (e.g. '#ifndef _MYHEADER_H_', etc.), and/or '#pragma once' too.
#
# - For each #if ... #endif sequence, automatically adds a comment
#   after the #endif (and the #else clause, if present) to denote
#   which preprocessor condition governed the #if/#else/#endif
#   block that is being closed by #else or #endif. 
# 
#   The preprocessor conditionals in C/C++ can be very non-obvious
#   and confusing when they're deeply nested and/or have complex 
#   #else or #elif clauses. Unfortunately they generally can't be
#   properly indented according to their nesting, and it appears
#   there are no editors that automatically tell you what condition
#   originally opened the #if or #else block you're in (at least
#   Emacs doesn't seem to support this like it does for all other
#   symbolic block delimiters (i.e. {}, (), [])).
#
#    Therefore, this feature aims to remedy this problem without
#    altering the preprocessor syntax.
#
# Copyright 2014 Matt T. Yourst <yourst@yourst.com>
#

use integer;
use warnings;

use Cwd qw(realpath);
use File::Basename qw(dirname);
use File::stat;
use DateTime;

#! autoimport {
#! } # (end autoimport)

#++MTY TODO:
...
